theme: jekyll-theme-minimal
title: **David's Page**
description: CS250 assignment fun!
![doggo](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.nationalgeographic.com%2Fanimals%2Farticle%2Frescue-dogs-behavior-animals&psig=AOvVaw0Q3KJ_lutluZOThK6GQnqh&ust=1644019252948000&source=images&cd=vfe&ved=0CAgQjRxqFwoTCMCnnI_f5PUCFQAAAAAdAAAAABAD)
